ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-black
      - mdformat-config
      - mdformat-gfm
      - mdformat-web
      - mdformat-mkdocs

