name: leap-docs-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sphinx==4.5.0
  - jupyter-book==0.15.1
  - sphinxcontrib-bibtex
  - pip
  - pip:
    - sphinx-jinja
    - pre-commit
    - lxml_html_clean
