name: leap-docs-env
channels:
  - conda-forge
dependencies:
  - sphinx==4.5.0
  - jupyter-book==0.12.3
  - sphinxcontrib-bibtex
  - pip
  - pip:
    - sphinx-jinja
    - pre-commit
    - lxml_html_clean
